---
- name: Set up passwordless SSH authentication
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Get the SSH public key of the Ansible control node
      command: "cat ~/.ssh/id_rsa.pub"
      register: ssh_pub_key

    - name: Add SSH public key to the Ubuntu instances
      authorized_key:
        user: "{{ item.user }}"
        state: present
        key: "{{ ssh_pub_key.stdout }}"
        path: "/home/{{ item.user }}/.ssh/authorized_keys"
      loop:
        - { user: "ubuntu", host: "{{ item.public_ip }}" }
      delegate_to: "{{ item.public_ip }}"
      when: item.image == "ubuntu"

    - name: Add SSH public key to the CentOS instance
      authorized_key:
        user: "{{ item.user }}"
        state: present
        key: "{{ ssh_pub_key.stdout }}"
        path: "/home/{{ item.user }}/.ssh/authorized_keys"
      loop:
        - { user: "centos", host: "{{ item.public_ip }}" }
      delegate_to: "{{ item.public_ip }}"
      when: item.image == "centos"
